[build]
  command = "pnpm install --no-frozen-lockfile && pnpm build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "18"
  PNPM_FLAGS = "--no-frozen-lockfile"

[dev]
  command = "pnpm dev"
  framework = "remix"

[[headers]]
  for = "/build/*"
    [headers.values]
      "Cache-Control" = "public, max-age=31560000, immutable"