[build]
  command = "pnpm run build"
  publish = "build/client"

[dev]
  command = "pnpm run dev"
  framework = "vite"

[[edge_functions]]
  path = "/*"
  function = "remix"

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"