[build]
  command = "pnpm run build"
  publish = "build/client"
  functions = "build/server"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/remix-server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31560000, immutable"